import 'package:flutter/material.dart';
import 'package:snuggle_mobile/app/theme/snuggle_palette.dart';

class SnugglePalettes {
  static const String defaultId = 'love_sprout';

  static const List<SnugglePalette> all = <SnugglePalette>[
    SnugglePalette(
      id: 'love_sprout',
      label: 'LoveSprout Default',
      isDark: false,
      background: Color(0xFFFFF7F4),
      surface: Color(0xFFFFFFFF),
      surfaceAlt: Color(0xFFFFE8ED),
      primary: Color(0xFFFF6F91),
      secondary: Color(0xFF7BD8A0),
      accent: Color(0xFFFFD166),
      text: Color(0xFF2E2230),
      mutedText: Color(0xFF8B7788),
      border: Color(0xFFF3C9D3),
      success: Color(0xFF43A047),
      warning: Color(0xFFF9A825),
      danger: Color(0xFFE53935),
      heroGradientStart: Color(0xFFFFA4B8),
      heroGradientEnd: Color(0xFFFF6F91),
    ),
    SnugglePalette(
      id: 'snuggle_sky',
      label: 'Snuggle Sky',
      isDark: false,
      background: Color(0xFFF5FAFF),
      surface: Color(0xFFFFFFFF),
      surfaceAlt: Color(0xFFE6F1FF),
      primary: Color(0xFF78A6FF),
      secondary: Color(0xFFFFB7A5),
      accent: Color(0xFFC7B8FF),
      text: Color(0xFF202A44),
      mutedText: Color(0xFF71809A),
      border: Color(0xFFC8DCF7),
      success: Color(0xFF2E7D32),
      warning: Color(0xFFF9A825),
      danger: Color(0xFFD32F2F),
      heroGradientStart: Color(0xFFA8C5FF),
      heroGradientEnd: Color(0xFF78A6FF),
    ),
    SnugglePalette(
      id: 'cuddleberry',
      label: 'Cuddleberry',
      isDark: false,
      background: Color(0xFFFFF5FA),
      surface: Color(0xFFFFFFFF),
      surfaceAlt: Color(0xFFF9DCEB),
      primary: Color(0xFFD94F8C),
      secondary: Color(0xFFA78BFA),
      accent: Color(0xFFFFB3C7),
      text: Color(0xFF342037),
      mutedText: Color(0xFF8E6E91),
      border: Color(0xFFEDBED5),
      success: Color(0xFF2E7D32),
      warning: Color(0xFFF57F17),
      danger: Color(0xFFC62828),
      heroGradientStart: Color(0xFFE88AB0),
      heroGradientEnd: Color(0xFFD94F8C),
    ),
    SnugglePalette(
      id: 'honey_peach',
      label: 'Honey Peach',
      isDark: false,
      background: Color(0xFFFFF8EC),
      surface: Color(0xFFFFFFFF),
      surfaceAlt: Color(0xFFFFE6C7),
      primary: Color(0xFFFF8A65),
      secondary: Color(0xFFF7C948),
      accent: Color(0xFF9FD8A8),
      text: Color(0xFF3A2A1F),
      mutedText: Color(0xFF907761),
      border: Color(0xFFF3D2A8),
      success: Color(0xFF388E3C),
      warning: Color(0xFFF57C00),
      danger: Color(0xFFD84315),
      heroGradientStart: Color(0xFFFFB98A),
      heroGradientEnd: Color(0xFFFF8A65),
    ),
    SnugglePalette(
      id: 'mint_cocoa',
      label: 'Mint Cocoa',
      isDark: false,
      background: Color(0xFFF5FBF7),
      surface: Color(0xFFFFFFFF),
      surfaceAlt: Color(0xFFDFF3E7),
      primary: Color(0xFF4FB286),
      secondary: Color(0xFFC89B7B),
      accent: Color(0xFFF3DFA2),
      text: Color(0xFF25332D),
      mutedText: Color(0xFF66766F),
      border: Color(0xFFC7E4D2),
      success: Color(0xFF2E7D32),
      warning: Color(0xFFEF6C00),
      danger: Color(0xFFC62828),
      heroGradientStart: Color(0xFF8AC9AD),
      heroGradientEnd: Color(0xFF4FB286),
    ),
    SnugglePalette(
      id: 'moonlit_rose',
      label: 'Moonlit Rose',
      isDark: true,
      background: Color(0xFF151A34),
      surface: Color(0xFF20264A),
      surfaceAlt: Color(0xFF2D3563),
      primary: Color(0xFFFF8FAB),
      secondary: Color(0xFF8EC5FF),
      accent: Color(0xFFF6D365),
      text: Color(0xFFF9F4FF),
      mutedText: Color(0xFFB9B4D6),
      border: Color(0xFF414977),
      success: Color(0xFF81C784),
      warning: Color(0xFFFFD54F),
      danger: Color(0xFFEF9A9A),
      heroGradientStart: Color(0xFF46508C),
      heroGradientEnd: Color(0xFF2D3563),
    ),
    SnugglePalette(
      id: 'cherry_milk',
      label: 'Cherry Milk',
      isDark: false,
      background: Color(0xFFFFF6F6),
      surface: Color(0xFFFFFFFF),
      surfaceAlt: Color(0xFFFFE1E4),
      primary: Color(0xFFE84855),
      secondary: Color(0xFF6CC5B8),
      accent: Color(0xFFFFC857),
      text: Color(0xFF30242A),
      mutedText: Color(0xFF8A747C),
      border: Color(0xFFF4B8BF),
      success: Color(0xFF2E7D32),
      warning: Color(0xFFF9A825),
      danger: Color(0xFFC62828),
      heroGradientStart: Color(0xFFF07F88),
      heroGradientEnd: Color(0xFFE84855),
    ),
  ];

  static SnugglePalette byId(String id) {
    return all.firstWhere(
      (palette) => palette.id == id,
      orElse: () => all.first,
    );
  }
}
